### PR TITLE
Invoca Update 1

### PR DESCRIPTION
**Pull request by austinquinn**
Wrote a progress update with some reference photos. Hopefully the ![alt text] links still work after merging.

### CODE REVIEW

**Comment by syoh** [comment]
@austinquinn Could you turn on GitHub pages on the repository? The instruction video shows you how: https://ucsb-ds-capstone-2021.github.io/class/software-tools_create-update-pages.html

**Comment by austinquinn** [comment]
Does it work now?

**Comment by syoh** [comment]
The page does not work for me. If the setup is identical to the instruction video, Invoca team update page would show up here: https://austinquinn.github.io/ucsb-ds-capstone-2021.github.io/projects/invoca/update1.html

DM me on Gitter before 12 pm and I can help you figure this out on a Zoom call

**Comment by austinquinn** [comment]
The update page appears in that link now ^ except for the pictures because my links used ucsb-ds-capstone-2021 as the repo (instead of austinquinn). Hopefully it will all show up when in the main ucsb-ds-capstone-2021 repo

**Pull request merged**
